{% set name = "cesard" %}
{% set version = "1.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 274ea7760413649020add13101d06a69cbce5a032b092f0e8ebbc1bd1acc9f89

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - asf_search
    - gdal >=3.5.0
    - geopandas
    - lxml
    - multiformats >=0.3.1
    - numpy <2.0
    - pandas
    - pyroSAR >=0.33.1
    - pystac >=1.8.0,<1.11.0
    - python >={{ python_min }}
    - python-dateutil
    - requests
    - scipy
    - spatialist >=0.16.0

test:
  imports:
    - cesard
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/SAR-ARD/cesard
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Central SAR ARD Tools

  description: |
    Central functionalities for creating Synthetic Aperture Radar (SAR) Analysis Ready Data (ARD) products.
  doc_url: https://cesard.readthedocs.io
  dev_url: https://github.com/SAR-ARD/cesard

extra:
  recipe-maintainers:
    - johntruckenbrodt
